#!/bin/bash
# @sacloud-once
# @sacloud-desc-begin
#   The CONBU pre-setup startup script created by FoxBoxsnet
#   デフォルトユーザー(ubuntu)を削除します。
# @sacloud-desc-end
# @sacloud-require-archive distro-ubuntu
set -e
# デフォルトユーザーの削除
#userdel -r "ubuntu"
# 新規ユーザー作成
useradd -s /bin/bash -m "${ユーザ名}"
echo "${ユーザ名}:${パスワード}" | /usr/sbin/chpasswd
# sudo グループに追加
gpasswd -a "${ユーザ名}" sudo
cat << EOF1 | sudo tee /etc/sudoers.d/${ユーザ名} >> /dev/null
${ユーザ名} ALL=(ALL) NOPASSWD:ALL
EOF1
# slack 通知
curl -sfSL \
  -X POST \
  --data-urlencode 'payload={"channel": "#18b-notice-info", "username": "usacloud", "text": "`18b-cc-dhcp01` deploy complete for Created by terraform."}' \
  "https://${SlackのWebhook URL}"
